### ISSUE TITLE
Extra requests when "Stop Drop Requests" is enabled for non-Proxy traffic

### ISSUE THREAD

**Issue by ngregoire** [simioni87/auth_analyzer#20] opened 2021-08-12 17:03 UTC
Not sure if I found a bug or totally misunderstood what should happen. Here's the details...

How to reproduce:
- disable "Only proxy traffic"
- enable "Stop Drop Requets"
- go to Repeater, emit a request
- check the extension tab and/or Loger++ logs

Outcome:
- two entries in the extension logs tab, the first one displaying "No response to show" for the unmodified request
- three exchanges in Logger++ (1 from Repeater, 2 from the extension)

Expected outcome:
- one entry in the extension logs tab, displaying "No response to show" for the unmodified request
- one exchange in Logger++ (from the extension)

Possible workaround: I could use "Repeat Request" from the extension contextual menu as a work-around (I tried, no extra requests are sent). Only problem: I can't map this action to a shortcut unlike Repeater's Send button. Efficiency--

And thanks for the extension!

**Comment by simioni87** [comment] 2021-08-14 03:22
Your expectation is correct if you have **one** session set. Could it be that you have more than one session set?
![grafik](https://user-images.githubusercontent.com/37290182/129432625-cd17f073-41e6-4351-98f5-028c43774dc5.png)

Furthermore, I assume that you sent a request to the repeater which has no response yet (means the IHttpRequestResponse object has no response message). For this reason the Auth Analyzer displays "No response to show" at the original response...

**Comment by ngregoire** [comment] 2021-08-14 13:42
"No response to show": got it, thanks! Extra requests: I went through my tests again, I confirm the outcome with a single session. Details below...

![bug-authanalyzer_1](https://user-images.githubusercontent.com/4039324/129447983-82370b41-efc6-44cb-912a-75f5dab135ca.png)

Here we have two lines in the extension tab, but I think we should have only one (the one related to the ReproBug session). Is my understanding correct?

![bug-authanalyzer_2](https://user-images.githubusercontent.com/4039324/129447989-eafbf817-63a8-4a63-a9b9-06c13f9261b3.png)

That's imo the weirdest part (taken from Logger++ logs):
- why is the Repeater request not blocked?
- why is the extension sending two requests for a single session?

**Comment by ngregoire** [comment] 2021-08-14 13:44
Another point: are these two way of doing it equivalent? If not, what are the expected differences?

- call "Repeat request" from the extension's contextual menu
- send from Repeater, with "Only proxy traffic" disabled and "Drop requests" enabled

**Comment by simioni87** [comment] 2021-08-15 02:59
"why is the Repeater request not blocked?": Drop Original Request drops only proxy requedts. You can use it to test idempotent operations while navigating through a web app. 
"why is the extension sending two requests for a single session?": Indeed, this is weird. I assume another extension is also repeating the same request and therefore the auth analyzer is invoked twice. Pleace disable all other extensions and retry.
Repeat request from context menu repeats the selected request for all defined sessions but no the original one. Hope that helps...

**Comment by ngregoire** [comment] 2021-08-16 11:16
Thanks for all these responses, I start to get it!

If the following points are already documented somewhere, I'm sorry but I missed it. If not, maybe adding them to the README?
- "Drop Original Request" only applies to Proxy
- "Repeat request" repeats for all defined sessions, except the original one

Regarding the "two requests for a single session", I retried after disabling all extensions except AuthAnalyzer. Same outcome. I added a sniffer just to be sure, there's indeed 3 requests sent. Did you manage to reproduce this behavior?

**Comment by simioni87** [comment] 2021-08-16 13:52
I am not able to reproduce the behaviour. The request can only be processed twice if the processHttpMessage method of the HttpListener class is invoked twice. This method is invoked by the Burp Suite. Looking at the Logger+ Output shows that a request of an extension, followed by the repeater request and after that another request sent by an extension. How is it possible that the first request is sent by the extension if your repeater request is not sent yet?

**Comment by ngregoire** [comment] 2021-08-16 14:10
_How is it possible that the first request is sent by the extension if your repeater request is not sent yet?_ Good question ;-) Given this order may change, I'd bet on a time/display glitch in Logger++ (maybe that the response was received before, despite the request being sent after).

I'll keep digging!!

**Comment by simioni87** [comment] 2021-08-16 14:34
Okay, got it:
You switched to "Drop Original Requests" and therefore the Auth Analyzer repeats the Request if the IHttpRequestResponse has no response yet. However, since only Proxy requests are really dropped, the auth analyzer is invoked a second time as soon as the response is received. 
The following change within HttpListener will fix this issue:
`if(config.isRunning() && (!messageIsRequest || (messageIsRequest && config.isDropOriginal() && toolFlag == IBurpExtenderCallbacks.TOOL_PROXY)))`

Thanks for reporting it

**Comment by ngregoire** [comment] 2021-08-16 22:36
_[...] the auth analyzer is invoked a second time [...]_ -> Good catch! Glad my analysis was correct. Looking forward to testing v.1.1.8 ;-)

_[...] The following change within HttpListener will fix this issue[...]_ -> Thanks! For reference, here's a [permalink](https://github.com/simioni87/auth_analyzer/blob/b38bf4dc19e7208ce798492122a46e9602594b00/src/com/protect7/authanalyzer/controller/HttpListener.java#L28) to the relevant line

**Comment by simioni87** [comment] 2021-12-14 06:27
Fixed with the last release. Thanks for reporting ngregoire.

**Closed by simioni87** 2021-12-14 06:27 UTC
